SELECT
 vhh.AP_ORG_ID
 , oa.VCHR_VEND_ID
 , vhh.TERMS_DC
 , vhh.INVC_DT
 , vhh.DUE_DT
 , oa.S_STATUS_CD
 , vhh.INVC_AMT
 , oa.PAID_AMT
 , oa.PAY_AMT

FROM DELTEKCP.DELTEK.OPEN_AP oa

LEFT JOIN DELTEKCP.DELTEK.VCHR_HDR_HS vhh
	ON vhh.VCHR_KEY = oa.VCHR_KEY
;