SELECT
 vhh.AP_ORG_ID
 , oa.VCHR_VEND_ID
 , vhh.TERMS_DC
 , vhh.INVC_DT
 , vhh.DUE_DT
 , oa.S_STATUS_CD
 , vhh.INVC_AMT
 , oa.PAID_AMT
 , oa.PAY_AMT
 , (vhh.INVC_AMT - oa.PAID_AMT) AS BALANCE_DUE
 , CASE 
	WHEN DATEDIFF(d,vhh.DUE_DT,GETDATE())< 0 THEN 0
	ELSE DATEDIFF(d,vhh.DUE_DT,GETDATE())
	END AS AGING

FROM DELTEKCP.DELTEK.OPEN_AP oa

LEFT JOIN DELTEKCP.DELTEK.VCHR_HDR_HS vhh
	ON vhh.VCHR_KEY = oa.VCHR_KEY
;	