-- Script pulls financial information from the FS reporting tables

SELECT 
	DELTEKCP.DELTEK.FS_LN.FS_CD, 
	DELTEKCP.DELTEK.FS_LN.FS_LN_KEY,
	DELTEKCP.DELTEK.FS.COMPANY_ID,
	DELTEKCP.DELTEK.FS_LN.FS_MAJOR_NO,
	DELTEKCP.DELTEK.FS_LN.FS_GRP_NO,
	DELTEKCP.DELTEK.FS_LN.FS_LN_NO,
	DELTEKCP.DELTEK.FS_LN.FS_MAJOR_DESC,
	DELTEKCP.DELTEK.FS_LN.FS_GRP_DESC,
	DELTEKCP.DELTEK.FS_LN.FS_LN_DESC,
	DELTEKCP.DELTEK.FS_LN.FS_RVRS_SGN_FL,
	DELTEKCP.DELTEK.FS_SUM.ACCT_ID,
	DELTEKCP.DELTEK.FS_SUM.ORG_ID,
	DELTEKCP.DELTEK.FS_SUM.FY_CD,
	DELTEKCP.DELTEK.FS_SUM.BEG_AMT,
	DELTEKCP.DELTEK.FS_SUM.PD_1_AMT AS PD_1,
	DELTEKCP.DELTEK.FS_SUM.PD_2_AMT AS PD_2,
	DELTEKCP.DELTEK.FS_SUM.PD_3_AMT AS PD_3,
	DELTEKCP.DELTEK.FS_SUM.PD_4_AMT AS PD_4,
	DELTEKCP.DELTEK.FS_SUM.PD_5_AMT AS PD_5,
	DELTEKCP.DELTEK.FS_SUM.PD_6_AMT AS PD_6,
	DELTEKCP.DELTEK.FS_SUM.PD_7_AMT AS PD_7,
	DELTEKCP.DELTEK.FS_SUM.PD_8_AMT AS PD_8,
	DELTEKCP.DELTEK.FS_SUM.PD_9_AMT AS PD_9,
	DELTEKCP.DELTEK.FS_SUM.PD_10_AMT AS PD_10,
	DELTEKCP.DELTEK.FS_SUM.PD_11_AMT AS PD_11,
	DELTEKCP.DELTEK.FS_SUM.PD_12_AMT AS PD_12
FROM 
	DELTEKCP.DELTEK.FS_LN,
	DELTEKCP.DELTEK.FS_SUM,
	DELTEKCP.DELTEK.FS,
	DELTEKCP.DELTEK.FS_LN_ACCT
WHERE
	-- Join FS_LN and FS_LN_ACCT tables:
	DELTEKCP.DELTEK.FS_LN.FS_CD=DELTEKCP.DELTEK.FS_LN_ACCT.FS_CD
	AND	DELTEKCP.DELTEK.FS_LN.FS_LN_KEY=DELTEKCP.DELTEK.FS_LN_ACCT.FS_LN_KEY
	AND DELTEKCP.DELTEK.FS_LN.COMPANY_ID=DELTEKCP.DELTEK.FS_LN_ACCT.COMPANY_ID
	-- Join FS_LN and FS tables:
	AND DELTEKCP.DELTEK.FS_LN.FS_CD = DELTEKCP.DELTEK.FS.FS_CD
	AND DELTEKCP.DELTEK.FS_LN.COMPANY_ID = DELTEKCP.DELTEK.FS.COMPANY_ID
	-- Join FS_LN_ACCT and FS_SUM tables:
	AND	DELTEKCP.DELTEK.FS_LN_ACCT.ACCT_ID=DELTEKCP.DELTEK.FS_SUM.ACCT_ID
	AND DELTEKCP.DELTEK.FS_LN_ACCT.COMPANY_ID=DELTEKCP.DELTEK.FS_SUM.COMPANY_ID
	
--	AND
--	DELTEKCP.DELTEK.FS_LN.FS_CD = 'ISELC'
