SELECT
	hs.FY_CD
	, hs.PD_NO
	, hs.CASH_RECPT_NO
	, h.LN_NO
	, h.ORG_ID
	, h.PROJ_ID
	, h.ACCT_ID
	, h.CHK_NO
	, h.CUST_ID
	, h.INVC_ID
	, h.TRN_DESC
	, h.TRN_AMT

FROM DELTEKCP.DELTEK.CASH_RECPT_HDR_HS hs
LEFT JOIN DELTEKCP.DELTEK.CASH_RECPT_TRN_HS h
ON hs.CASH_RECPT_HDR_KEY = h.CASH_RECPT_HDR_KEY

ORDER BY
	hs.FY_CD
	, hs.PD_NO
	, hs.CASH_RECPT_NO
	, h.LN_NO
;